### ISSUE TITLE
Mejora clase Point

### ISSUE THREAD

**Issue by jliriano** [jliriano/IWVG.SwC.JoelLiriano#1]
Agregar método ``modifyPoint`` a la clase Point para tener la funcionalidad de cambiar las coordenadas de un punto existente.  
Actualizar test para incluir cobertura para el nuevo método.

[Ver detalles](https://github.com/jliriano/IWVG.SwC.JoelLiriano/wiki/Point#mejoras)

**Comment by miguelcalderons** [comment]
Esta en el branch issue#01
