### ISSUE TITLE
Mejora calse Fraction: invert

### ISSUE THREAD

**Issue by jliriano** [jliriano/IWVG.SwC.JoelLiriano#5]
Agregar método ``invert()`` para invertir la fracción. Agregar tests necesarios para dar cobertura de prueba a la nueva funcionalidad.

[Ver detalles](https://github.com/jliriano/IWVG.SwC.JoelLiriano/wiki/Fraction#mejoras)
[Repaso de conceptos sobre fracciones](https://github.com/jliriano/IWVG.SwC.JoelLiriano/wiki/Fraction#conceptos)

**Comment by miguelcalderons** [comment]
Esta en el branch issue#05
